# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude:
  
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  # - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/psf/black
  rev: 22.12.0
  hooks:
  - id: black
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.0.0
  hooks:
  - id: mypy
    # args: [--verbose]
    language: system  
    exclude: 
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    files: |
      (?x)^(
        .*\.py|
        .*\.py.in|
      )$


- repo: https://github.com/pocc/pre-commit-hooks
  rev: v1.3.5
  hooks:
  - id: clang-format
    args: [--style=file, -i]
  - id: clang-tidy
    args: [--quiet]
    

- repo: https://github.com/lorenzwalthert/precommit
  rev: v0.4.0
  hooks:
  - id: spell-check


